name: Generate Release PDF

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'

jobs:
  release_pdf:
    uses: hooyuser/pdf-ci-templates/.github/workflows/pdf-release.yml@main
    with:
      TEX_FILE_NAME: Topology
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
