name: Generate Release PDF

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '.gitignore'

jobs:
  release_pdf:
    uses: hooyuser/pdf-ci-templates/.github/workflows/pdf-release.yml@main
    with:
      TEX_FILE_NAME: Topology
