name: Generate Release PDF
on:
  push:
    paths-ignore:
      - 'README.md'

permissions:
  contents: write      # for creating/deleting releases
  pages: write         # for Pages deployment
  id-token: write      # required by configure-pages

env:
  TEX_FILE_NAME: Topology

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ${{ env.TEX_FILE_NAME }}.tex

      - name: Delete old Release
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            try {
              const { data: { id } } = await github.rest.repos.getLatestRelease({ owner, repo });
              await github.rest.repos.deleteRelease({ owner, repo, release_id: id });
            } catch {}

      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::latest_$(date +'%Y-%m-%d_%H-%M')"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: latest version
          body: Latest version of `${{ env.TEX_FILE_NAME }}.pdf`
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: ${{ env.TEX_FILE_NAME }}.pdf

      # ───────────────────────────────────────────────────────────
      # Deploy to GitHub Pages for inline PDF viewing:
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.TEX_FILE_NAME }}.pdf  # package Topology.pdf for Pages :contentReference[oaicite:2]{index=2}

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        # with:
          # artifact_name defaults to "github-pages"
          # token defaults to ${{ github.token }}
        # if you want the Pages URL in the job’s summary, add:
        # id: deployment
